development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: base_app_dev
  username: username
  password: password

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: base_app_test
  username: username
  password: password
